### PR TITLE
Issue/1175

### PR DESCRIPTION
**Pull request by temcdrm**
Resolves the CIMHub refactoring issue [#1175](https://github.com/gridappsd/goss-gridapps-d/issues/1175) and platform integration issue [#1176](https://github.com/gridappsd/goss-gridapps-d/issues/1176) 

Overview of changes:

- The Java and Python code has been moved to CIMHub
- The input data for the GridAPPS-D feeder models, Measurements and Houses is all under the ```platform``` subdirectory
- The Blazegraph URL and CIM namespace for the bash and Python scripts are configurable through ```envars.sh``` and ```cimhubconfig.json``` files under the ```platform``` directory
- Measurement and House mRIDs will now persist
- Faster insertion of Measurements, Houses and DER
- The number of houses on the 8500-node and 9500-node feeder has been reduced by command-line adjustment of the default 3.0 VA_PER_SQRT to a higher 3.75 VA_PER_SQFT. This change should mitigate overloads and voltage drops when running those two feeders with Houses. (A separate issue will be created to make further improvements to the Housing script.)

Pre-requisites for testing:

- clone the master branch of [CIMHub](https://github.com/gridappsd/cimhub) into a sibling directory to Powergrid-Models, e.g., ```~/src/CIMHub```. Only the Python scripts in ```CIMHub/utils``` are strictly required for platform maintenance, but a more complete test is recommended on this pull request. (A separate issue will be created to move the Python utilities into a PyPi deployment.)
- obtain the latest version 1.2.16 of opendsscmd [pull request #1447](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/1447). Then copy those files to ```/usr/local/bin``` or somewhere else on your path.
- ensure a recent build of GridLAB-D is on your path.

Test sequence for CIMHub:

- from ```~/src/CIMHub```, issue ```mvn clean install```
- having Blazegraph installed in a container, issue ```docker restart blazegraph```
- from ```~/src/CIMHub/example```, issue ```./example.sh arg```. The script should create OpenDSS and GridLAB-D models, then solve both of them.

Test sequence for Powergrid-Models:

- if Blazegraph is not still running, issue ```docker restart blazegraph```
- from ```~/src/Powergrid-Models/platform```, issue ```./test_all.sh```.  The script should create 11 CIM XML files, export each to OpenDSS and GridLAB-D, then solve each in OpenDSS and GridLAB-D. Except for the IEEE 37-bus model in GridLAB-D, all should solve and produce summary output as described in the ```platform/README.md``` file, **Comparing Test Results** section
- from ```~/src/Powergrid-Models/platform```, issue ```./import_all.sh```. The script should insert Measurements for 11 feeder models and Houses for 5 feeder models. It will then solve 5 feeder models with Houses in GridLAB-D only. (You may notice a warning about _FindSimObject_ failing to link some Measurements on the R2 feeder. There will be a separate issue created for this).
- from ```~/src/Powergrid-Models/platform/DER```, issue ```./insert_der/sh```. The script should insert several DER to the Transactive feeder model, which currently doesn't have any DER.
- from ```~/src/Powergrid-Models/platform/DER```, issue ```./test_der/sh```. The script should export and solve the augmented Transactive DER feeder model in both OpenDSS and GridLAB-D
- from ```~/src/Powergrid-Models/platform/DER```, issue ```./drop_der/sh```. The script should remove extra DER from the Transactive DER feeder model

Documentation Review:

- check ```~/src/Powergrid-Models/BLAZEGRAPH_IMPORT.md```. It has updated instructions for maintaining the platform feeder models, given that someone else has done the testing steps for any updates.

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/powergrid-models/88)

### CODE REVIEW

**Comment by temcdrm** [comment]
Alexander needs to review the conflict.

**Comment by temcdrm** [comment]
The conflicts have been resolved and retested with commits [c5b4f62](https://github.com/GRIDAPPSD/Powergrid-Models/pull/88/commits/c5b4f62aca2239090a07e8af10bf1d9234dc6a89) and [0f51ea7](https://github.com/GRIDAPPSD/Powergrid-Models/pull/88/commits/0f51ea78a4d2c373869ea993053e23a28284de22).  If the merge won't go automatically, it can go manually using the issue/1175 versions.

**Comment by poorva1209** [comment]
@temcdrm I still see conflicts with the three files mentioned above. Can you merge them with issue/1175 versions?
I can test and merge the pull request after that.

**Comment by poorva1209** [comment]
@temcdrm Do I need FNCs installed too to test this pull request?

**Comment by temcdrm** [comment]
No, you should not need FNCS to complete the tests.

**Comment by poorva1209** [comment]
Hey @temcdrm I am getting these errors while testing test_all.sh:

1. Last Error: Redirect File: "/home/gridappsd1/git/Powergrid-Models/taxonomy/new_R2_12_47_2/Master.dss" Not Found.
2. ERROR    [2000-01-01 00:00:00 EST] : commit_voltdump: voltdump - Unable to map voltage property of node:5908 - sx2952007c
ERROR    [2000-01-01 00:00:00 EST] : model_commit_failed
ERROR    [2000-01-01 00:00:00 EST] : exec halted: commit failure
This error is repeated multiple times. 
3. Traceback (most recent call last):
  File "Compare_Cases.py", line 389, in <module>
    write_comparisons (dir1, dir2, dir3, root, bases)
  File "Compare_Cases.py", line 256, in write_comparisons
    print (key, s1[key], s2[key], file=flog)
KeyError: 'Status'

Let me know how to resolve them or let me know when you are available I can give you a call.

**Comment by temcdrm** [comment]
From this directory: https://github.com/GRIDAPPSD/Powergrid-Models/tree/issue/1175/taxonomy 

Please complete the steps "Updating the Taxonomy Feeders" and then "GridLAB-D to OpenDSS Conversion" as described in the README.md.  It it works, I will add this step to the platform maintenance instructions.

**Comment by poorva1209** [comment]
Getting this while updating taxanomy feeders:

gridappsd1@gridappsd1-VirtualBox:~/git/Powergrid-Models/taxonomy/base_taxonomy$ ./run_all_new.sh 
ERROR    [INIT] : keyword 'polar' is not valid for property mode
new_R1-12.47-1.glm(16): property mode of voltdump:0 could not be set to 'polar'
new_R1-12.47-1.glm(14): load failed at or near 'object voltd...'
FATAL    [INIT] : shutdown after command line rejected
ERROR    [INIT] : keyword 'polar' is not valid for property mode

**Comment by temcdrm** [comment]
Please "git pull" and then restart from "python3 FixTransformers.py"

**Comment by poorva1209** [comment]
That moved things forward. Now I am getting highlighted error for every simulation: 

ERROR    [2000-01-01 00:00:00 EST] : commit_voltdump: voltdump - Unable to map voltage property of node:1282 - R5-35-00-1_tn_1
ERROR    [2000-01-01 00:00:00 EST] : model_commit_failed
ERROR    [2000-01-01 00:00:00 EST] : exec halted: commit failure
FATAL    [2000-01-01 00:00:00 EST] : shutdown after simulation stopped prematurely
FATAL    [2000-01-01 00:00:00 EST] : environment startup failed: Success

**Comment by temcdrm** [comment]
What does `gridlabd --version` say?

For now, just skip over `./run_all_new.sh`

**Comment by poorva1209** [comment]
GridLAB-D version is: GridLAB-D 4.1.0-18109 (Lugo [46541cb8:master:Mod]) 64-bit LINUX RELEASE
Let me know if I need to update it. 

Skipping ./run_all_new.sh for now and moving to "GridLAB-D to OpenDSS Conversion" section.

**Comment by temcdrm** [comment]
Mine is newer: GridLAB-D **4.3.0**-18617 (**Navajo** [6c983d8d:develop:Mod]) 64-bit LINUX RELEASE and built from the `develop` branch.  I'm not sure what version GridAPPS-D is using for the platform.

**Comment by poorva1209** [comment]
GridAPPS-D has 4.3 too. I will update mine.

**Comment by poorva1209** [comment]
I updated to gridlab-d's last stable release version 4.2. With that the simulation ran successfully. I could also run test_all.sh under platform. For running import_all.sh, I had to additionally install numpy, SPARQLWrapper and pandas modules. All the tests you mentioned runs successfully. 

Do we need to update cim2glm library or the one we have under cnf/release would still work with the this pull request changes. We need to move cnf folder to CimHub as well later. I think we need to change the structure of src/main in CIMHub a little bit before we can connect the releases made in CimHub to platform. But if the current cim2glm works then we can do that after merging this pull request. 

@tonya1 Please create blazegraph:issue1175 container with issue/1175 branch. I will test it the platform before merging this pull request with the platform.

**Comment by temcdrm** [comment]
- pandas is required for inserting houses.  I can add that and other dependencies to the requirements.
- the old cim2glm library should still work, until this pull request is actually used to make new feeder models, houses and measurements for the platform
- the mRIDs are persistent, but they may differ from those currently in the platform. I think the persistent mRIDs were not fully adopted into the platform when first implemented
- right now, CIMHub/src only contains the Java code. There is companion code under CIMHub/utils that could be deployed onto PyPi as a new cimhub_utils package. When that happens, the Python code should also be moved under CIMHub/src, right?

**Comment by temcdrm** [comment]
There are some hard-coded namespaces and port numbers for Blazegraph in the GOSS-GridAPPS-D repository.  These should be handled through the _cimhubconfig.json file_

tom@uvm:~/src/GOSS-GridAPPS-D$ grep -r sparql *.*

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/BGPowergridModelDataManagerImpl.java:		//BGPowergridModelDataManagerImpl bg = new BGPowergridModelDataManagerImpl("http://localhost:9999/blazegraph/namespace/kb/sparql");

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/BGPowergridModelDataManagerImpl.java:		BGPowergridModelDataManagerImpl bg = new BGPowergridModelDataManagerImpl("http://192.168.99.100:8889/bigdata/namespace/kb/sparql");

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/BGPowergridModelDataManagerImpl.java:		bg.endpointNSURL = "http://localhost:8889/bigdata/sparql";

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/BGPowergridModelDataManagerImpl.java://			return endpointBaseURL+"/sparql";

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/BGPowergridModelDataManagerImpl.java://		return endpointBaseURL+"/namespace/"+modelId+"/sparql";

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/handlers/BlazegraphQueryHandler.java:	public static final String DEFAULT_ENDPOINT =  "http://blazegraph:8080/bigdata/namespace/kb/sparql";

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/handlers/BlazegraphQueryHandler.java:		QueryExecution qexec = QueryExecutionFactory.sparqlService (endpoint, query);

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/data/handlers/BlazegraphQueryHandler.java:		QueryExecution qexec = QueryExecutionFactory.sparqlService (endpoint, query);

gov.pnnl.goss.gridappsd/src/gov/pnnl/goss/gridappsd/testmanager/TestManagerQueryFactory.java:		QueryHandler queryHandler = new BlazegraphQueryHandler(bgHost+"/bigdata/namespace/kb/sparql", null, "1", "manager");

gov.pnnl.goss.gridappsd/conf/pnnl.goss.gridappsd.cfg:blazegraph.ns.path = http://localhost:8889/bigdata/sparql

gov.pnnl.goss.gridappsd/conf/pnnl.goss.gridappsd.cfg:blazegraph.host.path = http://blazegraph:8080/bigdata/namespace/kb/sparql

**Comment by temcdrm** [comment]
That grep turns up empty from the Powergrid-Models repository

**Comment by temcdrm** [comment]
tom@uvm:~/src/CIMHub$ grep -r sparql *.*

cimhubconfig.json:  "blazegraph_url": "http://localhost:8889/bigdata/namespace/kb/sparql",
Binary file CIMHub.eap matches
queries.txt:	<http://localhost:9999/blazegraph/namespace/kb/sparql#1> a c:Analog.
queries.txt:  <http://localhost:9999/blazegraph/namespace/kb/sparql#1> c:IdentifiedObject.mRID "uuid".
queries.txt:  <http://localhost:9999/blazegraph/namespace/kb/sparql#1> c:IdentifiedObject.name "name".
queries.txt:  <http://localhost:9999/blazegraph/namespace/kb/sparql#1> c:Measurement.PowerSystemResource  <http://localhost:9999/blazegraph/namespace/kb/sparql#2>.
queries.txt:  <http://localhost:9999/blazegraph/namespace/kb/sparql#1> c:Measurement.Terminal <http://localhost:9999/blazegraph/namespace/kb/sparql#3>.
queries.txt:  <http://localhost:9999/blazegraph/namespace/kb/sparql#1> c:Measurement.phases "ABC" .
queries.txt:  <http://localhost:9999/blazegraph/namespace/kb/sparql#1> c:Measurement.measurementType "PNV"

README.md:* ```-u={http://localhost:8889/bigdata/namespace/kb/sparql} // blazegraph uri (if connecting over HTTP); defaults to http://localhost:8889/bigdata/namespace/kb/sparql```

README.md:In order to develop Python code for the CIM, it should suffice to _pip3 install sparqlwrapper_ and then
requirements.md:6. Support different CIM versions through [SPARQL](https://www.w3.org/TR/sparql11-query/) queries stored in separate XML files

**Comment by craig8** [comment]
Can you rebase this pull request or deal with the conflicts?

**Comment by temcdrm** [comment]
That didn't work before... just use the three files from this pull request.

**Comment by poorva1209** [comment]
@craig8  you can merge this : https://github.com/GRIDAPPSD/Powergrid-Models/pull/92 
It has all the commits from issue/1175 with conflicts resolved.

**Pull request merged**
