### PR TITLE
Feature/1289 (inserting DER)

### PR DESCRIPTION
**Pull request by temcdrm**
See https://github.com/GRIDAPPSD/Powergrid-Models/tree/feature/1289/DER for instructions in the README.md file. In order to test:

- Insert Transactive.xml into blazegraph from the blazegraph/test directory
- Run import.sh from the blazegraph directory; it will make a model without DER
- "grep battery *.glm" to verify no batteries in transactive2_base.glm
- "gridlabd test_run.glm" from the blazegraph directory should solve power flow
- from the Powergrid-Models/DER directory, run "insert.sh" to insert 5 batteries to the model
- Run import.sh again from the blazegraph directory; it should remake the model with 5 batteries
- "grep battery *.glm" should now indicate 5 battery instances in transactive2_base.glm
- "gridlabd test_run.glm" should successfully solve power flow again

We can use a similar mechanism to add DER for the CIM/DERMS interop test and sample app.

---
This change is [Reviewable](https://reviewable.io/reviews/gridappsd/powergrid-models/73)

### CODE REVIEW

**Comment by temcdrm** [comment]
Updated Transactive.xml to include the indentation fix from two weeks ago.  Also corrected/expanded the test instructions.

**Comment by xcosmos6** [comment]
I am still having trouble running the import.sh. It tells me that there's fatal error compiling due to 
"invalide flag: --release". So if I get rid of the "<release>11</release>" line, then it complains about:
"[ERROR] (use -source 7 or higher to enable diamond operator)"
What am I missing? Thanks.

**Comment by temcdrm** [comment]
What is your Java version?

___________________________________

Tom McDermott, Ph.D., PE, FIEEE
Modeling & Analysis Team, Distributed Systems Group
Solar Sub-sector Lead
Pacific Northwest National Laboratory
Phone: 509-375-4434
Thomas.McDermott@pnnl.gov<mailto:Thomas.McDermott@pnnl.gov>

**Comment by xcosmos6** [comment]
> What is your Java version?
> […](#)
> ___________________________________ Tom McDermott, Ph.D., PE, FIEEE Modeling & Analysis Team, Distributed Systems Group Solar Sub-sector Lead Pacific Northwest National Laboratory Phone: 509-375-4434 Thomas.McDermott@pnnl.gov<mailto:Thomas.McDermott@pnnl.gov> From: xcosmos6 <notifications@github.com> Sent: Monday, June 22, 2020 2:36 PM To: GRIDAPPSD/Powergrid-Models <Powergrid-Models@noreply.github.com> Cc: McDermott, Thomas E <thomas.mcdermott@pnnl.gov>; Author <author@noreply.github.com> Subject: Re: [GRIDAPPSD/Powergrid-Models] Feature/1289 (inserting DER) (#73) I am still having trouble running the import.sh. It tells me that there's fatal error compiling due to "invalide flag: --release". So if I get rid of the "11" line, then it complains about: "[ERROR] (use -source 7 or higher to enable diamond operator)" What am I missing? Thanks. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=0f8ec06a-533bffd3-0f8eea7f-0cc47adc5fce-65a12b9cf1e7a228&q=1&e=a4bc551d-5b19-4858-8f88-572b68d91455&u=https%3A%2F%2Fgithub.com%2FGRIDAPPSD%2FPowergrid-Models%2Fpull%2F73%23issuecomment-647781760>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=338e0a08-6f3b35b1-338e201d-0cc47adc5fce-86b714704c750211&q=1&e=a4bc551d-5b19-4858-8f88-572b68d91455&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACAUYT72WKAVWBVABPRZPHDRX7FFVANCNFSM4NSCQYFA>.

my java is 1.8.0_112

**Comment by temcdrm** [comment]
It needs to be something like 11.0.5

**Comment by poorva1209** [comment]
@temcdrm @tdtalbot 
Tom, I tested this pull request again with gridappsd/blazegraph:feature_1289. I ran import.sh and it is stuck at the following screen for the last 30 minutes and not coming out the script execution: 
image

Can you try it on the specified blazegraph container and see if it working for you. We want to close all pull requests this week.

**Comment by temcdrm** [comment]
- docker pull gridappsd/blazegraph:feature_1289
- docker run --name db1289 -d -p 8889:8080 gridappsd/blazegraph:feature_1289
- The model is already loaded, so skipping step 1. An alternative would be to remove that circuit first, and then load Transactive.xml
image

- Step 2 seems to work

tom@uvm:~/src/Powergrid-Models/blazegraph$ ./import.sh
SPARQL Query Time:    1.9676 for count banks
SPARQL Query Time:    0.2141 for count tanks
SPARQL Query Time:    0.1806 for count mesh Z
SPARQL Query Time:    0.1152 for count windings
SPARQL Query Time:    0.1765 for count XfmrCode Ratings
SPARQL Query Time:    0.1472 for count SC test
SPARQL Query Time:    0.8583 for count line phases
SPARQL Query Time:    0.1030 for count spacing XY
SPARQL Query Time:    0.3833 for base v
SPARQL Query Time:    0.1432 for breakers
SPARQL Query Time:    0.1982 for caps
SPARQL Query Time:    0.1287 for CN cables
SPARQL Query Time:    1.4237 for coordinates
SPARQL Query Time:    0.0816 for disconnectors
SPARQL Query Time:    0.0785 for fuses
SPARQL Query Time:    1.9261 for lines with code Z
SPARQL Query Time:    0.1465 for lines with instance Z
SPARQL Query Time:    0.1666 for spacings
SPARQL Query Time:    0.1128 for lines with spacing
SPARQL Query Time:    0.1071 for switches
SPARQL Query Time:    1.1733 for loads
SPARQL Query Time:    4.4006 for meas
SPARQL Query Time:    0.1452 for wires
SPARQL Query Time:    0.2888 for phase matrix
SPARQL Query Time:    0.1289 for xfmr core
SPARQL Query Time:    0.0864 for xfmr mesh
SPARQL Query Time:    0.1038 for xfmr windings
SPARQL Query Time:    0.0717 for reclosers
SPARQL Query Time:    0.1169 for regulators (banked)
SPARQL Query Time:    0.1555 for regulators (tanked)
SPARQL Query Time:    0.0290 for XF count for regulator sizing
SPARQL Query Time:    0.0202 for XF count for regulator sizing
SPARQL Query Time:    0.0493 for XF count for regulator sizing
SPARQL Query Time:    0.0393 for sectionalisers
SPARQL Query Time:    0.1069 for sequence matrix
SPARQL Query Time:    0.0895 for solar
SPARQL Query Time:    0.2164 for storage
SPARQL Query Time:    0.0764 for subs
SPARQL Query Time:    0.0810 for TS cables
SPARQL Query Time:    0.0910 for xfmr code OC test
SPARQL Query Time:    0.1246 for xfmr code ratings
SPARQL Query Time:    0.1232 for xfmr code SC test
SPARQL Query Time:    0.2305 for xfmr tanks
SPARQL Query Time:    0.1291 for xfmr banks
SPARQL Query Time:    0.0411 for feeders
SPARQL Query Time:    0.0964 for houses
SPARQL Query Time:    0.1081 for sync mach
SPARQL Query Time:    0.6561 for bus-equipment map
SPARQL Query Time:    0.7882 for voltage map
SPARQL Query Time:    0.4414 for current map
SPARQL Query Time:    0.1126 for list nodes
LoadAllMaps:         20.3762
CheckMaps:            0.0000
UpdateModelState:     0.0000
ApplyCurrentLimits:   0.0090
WriteDSSFile:         0.5103
WriteDSSCoordinates:  0.0176
WriteGLMFile:         0.4194
WriteJSONSymbolFile:  0.0487
WriteDictionaryFile:  0.1215
WriteLimitsFile:      0.0662
tom@uvm:~/src/Powergrid-Models/blazegraph$ 

- Step 3 works

om@uvm:~/src/Powergrid-Models/blazegraph$ grep battery *.glm
ieee13_base.glm:  object battery {
ieee13_base.glm:    battery_capacity 200000.0;
ieee13_base.glm:    use_internal_battery_model true;
ieee13_base.glm:    battery_type LI_ION;
ieee13_base.glm:  object battery {
ieee13_base.glm:    battery_capacity 13500.0;
ieee13_base.glm:    use_internal_battery_model true;
ieee13_base.glm:    battery_type LI_ION;
tom@uvm:~/src/Powergrid-Models/blazegraph$ 

- Step 4 successful

tom@uvm:~/src/Powergrid-Models/blazegraph$ gridlabd test_run.glm
WARNING  [INIT] : Daylight saving time (DST) is not handled correctly when using TMY2 datasets; please use TMY3 for DST-corrected weather data.
WARNING  [INIT] : Node:cap_cap_c88a does not have the same nominal voltage as its parent - copying voltage from parent.
WARNING  [INIT] : last warning message was repeated 3 times
WARNING  [INIT] : Using a 2x2 z-matrix, instead of geometric values, is an under-determined system. Ground and/or neutral currents will be incorrect.
Processing 2000-01-01 00:00:00 EST...
Core profiler results

Total objects               4328 objects
Parallelism                    1 thread
Total time                   2.0 seconds
  Core time                  1.7 seconds (86.0%)
    Compiler                 0.8 seconds (42.1%)
    Instances                0.0 seconds (0.0%)
    Random variables         0.0 seconds (0.0%)
    Schedules                0.0 seconds (0.0%)
    Loadshapes               0.0 seconds (0.0%)
    Enduses                  0.0 seconds (0.0%)
    Transforms               0.0 seconds (0.0%)
  Model time                 0.3 seconds/thread (14.0%)
Simulation time                0 days
Simulation speed               0 object.hours/second
Passes completed               2 passes
Time steps completed           1 timesteps
Convergence efficiency      2.00 passes/timestep
Read lock contention        0.0%
Write lock contention       0.0%
Average timestep              0 seconds/timestep
Simulation rate               0 x realtime

Model profiler results

Class            Time (s) Time (%) msec/obj
---------------- -------- -------- --------
substation         0.121     43.2%    121.0
climate            0.117     41.8%    117.0
triplex_node       0.009      3.2%      0.0
triplex_load       0.009      3.2%      0.0
triplex_line       0.007      2.5%      0.0
voltdump           0.006      2.1%      6.0
currdump           0.004      1.4%      4.0
transformer        0.003      1.1%      0.0
overhead_line      0.002      0.7%      0.0
capacitor          0.001      0.4%      0.2
regulator          0.001      0.4%      0.3
Total              0.280    100.0%      0.1

WARNING  [2000-01-01 00:00:00 EST] : last warning message was repeated 1279 times
tom@uvm:~/src/Powergrid-Models/blazegraph$ 

- Step 5 successful

tom@uvm:~/src/Powergrid-Models/DER$ ./insert.sh
reading identifiable instance mRIDs from transactive123_der_uuid.txt
1511 buses
41489 locations
Coordinate System acep_psil_CrsUrn _8170F091-8035-4CE7-ADDD-347A162BA20D Feeder _503D6E20-F499-4CC7-8051-971E23D0BF79
create DG_7 at node_7 CN _DFF482D6-3FF0-4EBF-8E65-2080ADF247DB location 1000.0000,1500.0000
create DG_18 at node_18 CN _330DF55E-CC72-4A2D-B658-FE1E144D29FD location 1500.0000,2325.0000
create DG_56 at node_56 CN _7D561DF5-FEB2-4B05-8A78-6F7D308CB775 location 2875.0000,1500.0000
create DG_57 at node_57 CN _54EBAF5B-D586-4917-A5D5-3A75632A9511 location 2325.0000,1850.0000
create DG_152 at node_152 CN _1F3DE495-B44F-402D-8AB0-FEFCADB996D2 location 1600.0000,1500.0000
saving identifiable instance mRIDs to transactive123_der_uuid.txt
tom@uvm:~/src/Powergrid-Models/DER$ 

- Step 6

tom@uvm:~/src/Powergrid-Models/DER$ cd ../blazegraph
tom@uvm:~/src/Powergrid-Models/blazegraph$ ./import.sh
SPARQL Query Time:    1.5316 for count banks
SPARQL Query Time:    0.0991 for count tanks
SPARQL Query Time:    0.1070 for count mesh Z
SPARQL Query Time:    0.0820 for count windings
SPARQL Query Time:    0.1157 for count XfmrCode Ratings
SPARQL Query Time:    0.1086 for count SC test
SPARQL Query Time:    0.4130 for count line phases
SPARQL Query Time:    0.0671 for count spacing XY
SPARQL Query Time:    0.1490 for base v
SPARQL Query Time:    0.0932 for breakers
SPARQL Query Time:    0.1507 for caps
SPARQL Query Time:    0.0992 for CN cables
SPARQL Query Time:    1.0972 for coordinates
SPARQL Query Time:    0.0608 for disconnectors
SPARQL Query Time:    0.0640 for fuses
SPARQL Query Time:    1.3453 for lines with code Z
SPARQL Query Time:    0.1161 for lines with instance Z
SPARQL Query Time:    0.0941 for spacings
SPARQL Query Time:    0.1028 for lines with spacing
SPARQL Query Time:    0.1228 for switches
SPARQL Query Time:    0.8848 for loads
SPARQL Query Time:    2.8729 for meas
SPARQL Query Time:    0.1824 for wires
SPARQL Query Time:    0.4445 for phase matrix
SPARQL Query Time:    0.1125 for xfmr core
SPARQL Query Time:    0.1098 for xfmr mesh
SPARQL Query Time:    0.0889 for xfmr windings
SPARQL Query Time:    0.0818 for reclosers
SPARQL Query Time:    0.0947 for regulators (banked)
SPARQL Query Time:    0.1410 for regulators (tanked)
SPARQL Query Time:    0.0189 for XF count for regulator sizing
SPARQL Query Time:    0.0202 for XF count for regulator sizing
SPARQL Query Time:    0.0119 for XF count for regulator sizing
SPARQL Query Time:    0.0374 for sectionalisers
SPARQL Query Time:    0.1083 for sequence matrix
SPARQL Query Time:    0.1236 for solar
SPARQL Query Time:    0.0775 for storage
SPARQL Query Time:    0.0709 for subs
SPARQL Query Time:    0.0675 for TS cables
SPARQL Query Time:    0.0636 for xfmr code OC test
SPARQL Query Time:    0.0930 for xfmr code ratings
SPARQL Query Time:    0.1223 for xfmr code SC test
SPARQL Query Time:    0.2248 for xfmr tanks
SPARQL Query Time:    0.0658 for xfmr banks
SPARQL Query Time:    0.0383 for feeders
SPARQL Query Time:    0.0681 for houses
SPARQL Query Time:    0.0976 for sync mach
SPARQL Query Time:    0.5649 for bus-equipment map
SPARQL Query Time:    0.5238 for voltage map
SPARQL Query Time:    0.3254 for current map
SPARQL Query Time:    0.0822 for list nodes
LoadAllMaps:         15.3562
CheckMaps:            0.0000
UpdateModelState:     0.0000
ApplyCurrentLimits:   0.0008
WriteDSSFile:         0.4841
WriteDSSCoordinates:  0.0246
WriteGLMFile:         0.3956
WriteJSONSymbolFile:  0.0470
WriteDictionaryFile:  0.1231
WriteLimitsFile:      0.0630
tom@uvm:~/src/Powergrid-Models/blazegraph$ 

- Step 7 fails, in that batteries don't appear in the new transactive2_base.glm, apparently due to a different Blazegraph namespace.  Change the second line of DER/transactive123_der.txt from this:

blazegraph_url,http://localhost:8889/bigdata/namespace/kb/sparql

To this:

blazegraph_url,http://localhost:8889/bigdata/sparql

- Repeat steps 5, 6 and 7.  Now it works as expected:

tom@uvm:~/src/Powergrid-Models/blazegraph$ grep battery *.glm
ieee13_base.glm:  object battery {
ieee13_base.glm:    battery_capacity 200000.0;
ieee13_base.glm:    use_internal_battery_model true;
ieee13_base.glm:    battery_type LI_ION;
ieee13_base.glm:  object battery {
ieee13_base.glm:    battery_capacity 13500.0;
ieee13_base.glm:    use_internal_battery_model true;
ieee13_base.glm:    battery_type LI_ION;
transactive2_base.glm:  object battery {
transactive2_base.glm:    battery_capacity 500000.0;
transactive2_base.glm:    use_internal_battery_model true;
transactive2_base.glm:    battery_type LI_ION;
transactive2_base.glm:  object battery {
transactive2_base.glm:    battery_capacity 500000.0;
transactive2_base.glm:    use_internal_battery_model true;
transactive2_base.glm:    battery_type LI_ION;
transactive2_base.glm:  object battery {
transactive2_base.glm:    battery_capacity 500000.0;
transactive2_base.glm:    use_internal_battery_model true;
transactive2_base.glm:    battery_type LI_ION;
transactive2_base.glm:  object battery {
transactive2_base.glm:    battery_capacity 500000.0;
transactive2_base.glm:    use_internal_battery_model true;
transactive2_base.glm:    battery_type LI_ION;
transactive2_base.glm:  object battery {
transactive2_base.glm:    battery_capacity 500000.0;
transactive2_base.glm:    use_internal_battery_model true;
transactive2_base.glm:    battery_type LI_ION;
tom@uvm:~/src/Powergrid-Models/blazegraph$ 

- Step 8 also works

tom@uvm:~/src/Powergrid-Models/blazegraph$ gridlabd test_run.glm
WARNING  [INIT] : Daylight saving time (DST) is not handled correctly when using TMY2 datasets; please use TMY3 for DST-corrected weather data.
WARNING  [INIT] : Node:cap_cap_c88a does not have the same nominal voltage as its parent - copying voltage from parent.
WARNING  [INIT] : last warning message was repeated 3 times
WARNING  [INIT] : Using a 2x2 z-matrix, instead of geometric values, is an under-determined system. Ground and/or neutral currents will be incorrect.
WARNING  [INIT] : last warning message was repeated 1279 times
WARNING  [INIT] : Node:node_152_stmtr is parented to a swing node and will get folded into it.
WARNING  [INIT] : event_gen:testgendev does not have a metrics object as a parent -- metrics are not calculated.
WARNING  [INIT] : Node:node_7_stmtr is parented to a swing node and will get folded into it.
WARNING  [2000-01-01 00:00:00 EST] : last warning message was repeated 3 times
WARNING  [2000-01-01 00:00:00 EST] : Restoration object not detected!

Core profiler results

Total objects               4345 objects
Parallelism                    1 thread
Total time                   2.0 seconds
  Core time                  1.5 seconds (73.6%)
    Compiler                 1.4 seconds (72.1%)
    Instances                0.0 seconds (0.0%)
    Random variables         0.0 seconds (0.0%)
    Schedules                0.0 seconds (0.0%)
    Loadshapes               0.0 seconds (0.0%)
    Enduses                  0.0 seconds (0.0%)
    Transforms               0.0 seconds (0.0%)
  Model time                 0.5 seconds/thread (26.5%)
Simulation time                0 days
Simulation speed               0 object.hours/second
Passes completed               2 passes
Time steps completed           1 timesteps
Convergence efficiency      2.00 passes/timestep
Read lock contention        0.0%
Write lock contention       0.0%
Average timestep              0 seconds/timestep
Simulation rate               0 x realtime

Model profiler results

Class            Time (s) Time (%) msec/obj
substation         0.236     44.6%    236.0
climate            0.176     33.3%    176.0
switch             0.022      4.2%      2.0
triplex_line       0.021      4.0%      0.0
triplex_node       0.020      3.8%      0.0
fault_check        0.013      2.5%     13.0
triplex_load       0.013      2.5%      0.0
voltdump           0.012      2.3%     12.0
currdump           0.007      1.3%      7.0
capacitor          0.003      0.6%      0.8
node               0.002      0.4%      0.0
overhead_line      0.002      0.4%      0.0
meter              0.001      0.2%      0.2
transformer        0.001      0.2%      0.0
Total              0.529    100.0%      0.1

tom@uvm:~/src/Powergrid-Models/blazegraph$

**Comment by temcdrm** [comment]
Summarizing, it worked with gridappsd/blazegraph:feature_1289, skipping the load of Transactive.xml because that feeder was already in Blazegraph.  Then at step 7, the second line of this file had to be changed, in order for the 5 new batteries to be included in simulation: https://github.com/GRIDAPPSD/Powergrid-Models/blob/feature/1289/DER/transactive123_der.txt

However, this change to the blazegraph_url would not have affected a "hang" in import.sh.  That probably had a different cause.

**Comment by poorva1209** [comment]
@temcdrm @tdtalbot
I was able to test this pull request. These are the steps I had to take to test this:

1. I have Java 8 so instead of using jar file created by Tom I changed pom.xml to use java 8 and ran 'mvn clean install' to create Java 8 compatible jar. 

   ```
               <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <compilerArgs>
                        <arg>-Xlint:deprecation</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

 2. I don't have gridlabd directly in my virtual box. I have it in the gridappsd container so to test solving power flow steps I had to copy all the relevant file inside the gridappsd container and then run it there. These files include transactive2_base.glm, test_run.glm and all the files in support folder. I also had to export GLPATH as follows:
   ```
        export GLPATH = /gridappsd/share/gridlabd:/gridappsd/lib/gridlabd:/gridappsd/bin

 3. Rest I followed all the steps as mentioned. `

**Pull request merged**
